server:
  port: 8888
  ssl:
    key-store-type: PKCS12
    key-store: classpath:certificate.p12
    key-store-password: pegasus12

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security_app
    username: postgres
    password: sec
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: security_app_schema
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  flyway:
    enabled: true  # Enable Flyway migration on startup
    locations: classpath:db/migration  # Path to your migration scripts
    baseline-on-migrate: true
    validate-on-migrate: false
    clean-disabled: false
    schemas: security_app_schema
    default-schema: security_app_schema

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true